# Tema
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

# Info personal
title: "Portfolio AWS - Manuela Ghiulai"
description: "Proyectos de AWS Cloud"
author: "Manuela Ghiulai"

# URLs
url: "https://n3lita.github.io"
baseurl: ""

# Configuración
markdown: kramdown
highlighter: rouge
